Facelift

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -41,12 +41,14 @@ inputs:
   should-create-pr:
     description: |
       An optional script to decide whether to open the Pull Request or not.
-      If there is a new version of CIRCT, the action will run the provided
-      script. A return value of 0 means "open the PR". A return value of 1
-      means "do not open the PR". Any other return value will cause the action
-      to exit with an error.
+      The script must accept a single positional argument (the new CIRCT
+      version). The script is only run when there is a new version of CIRCT.  A
+      return value of 0 means "open the PR". A return value of 1 means "do not
+      open the PR". Any other return value will cause the action to exit with
+      an error. Note, the default value 'true' is the shell built-in, not a
+      boolean value.
     type: string
-    default: ''
+    default: 'true'
   github-token:
     description: |
       A GitHub token with sufficient permissions to create Pull Requests
@@ -99,28 +101,28 @@ runs:
       id: open-pr
       shell: bash
       run: |
+        cd downstream
         VERSION=${{ steps.get-version-latest.outputs.version }}
-        if [[ ${{ steps.get-version-current.outputs.version }} != "$VERSION" ]]; then
-          if [[ -n "${{ inputs.should-create-pr }}" ]]; then
-            if $(downstream/${{ inputs.should-create-pr }} "$VERSION"); then
-              RESULT="0"
-            else
-              RESULT=$?
-            fi
-          else
-            RESULT="0"
-          fi
-          if [[ "$RESULT" -eq "0" ]]; then
-            echo "result=yes" >> $GITHUB_OUTPUT
-          elif [[ "$RESULT" -eq "1" ]]; then
-            echo "::notice::User provided ${{ inputs.should-create-pr }} returned 1, skipping PR creation..."
-            echo "result=no" >> $GITHUB_OUTPUT
-          else
-            echo "::error::User provided ${{ inputs.should-create-pr }} returned $RESULT, aborting..."
-            exit 1
-          fi
+        if [[ ${{ steps.get-version-current.outputs.version }} == "$VERSION" ]]; then
+          echo "::notice::Current version ($VERSION) == latest version, skipping PR creation..."
+          echo "result=false" >> $GITHUB_OUTPUT
+          exit 0
+        fi
+
+        if $(${{ inputs.should-create-pr }} "$VERSION"); then
+          RESULT="0"
         else
-          echo "result=no" >> $GITHUB_OUTPUT
+          RESULT=$?
+        fi
+
+        if [[ "$RESULT" -eq "0" ]]; then
+          echo "result=true" >> $GITHUB_OUTPUT
+        elif [[ "$RESULT" -eq "1" ]]; then
+          echo "::notice::User provided ${{ inputs.should-create-pr }} returned 1, skipping PR creation..."
+          echo "result=false" >> $GITHUB_OUTPUT
+        else
+          echo "::error::User provided ${{ inputs.should-create-pr }} returned $RESULT, aborting..."
+          exit 1
         fi
 
     ############################################################################
@@ -142,7 +144,7 @@ runs:
     # [2]: "base" is GitHub lingo for "the branch without your changes".
     ############################################################################
     - name: Create PR Metadata
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       shell: bash
       # Write a JSON object to the temporary file `metadata/metadata.json` that
       # contains information about what this job is going to do.  Populate four
@@ -259,7 +261,7 @@ runs:
     #
     # [3]: https://pandoc.org/
     - name: Generate PR Title
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       uses: docker://pandoc/core
       with:
         args: >-
@@ -270,7 +272,7 @@ runs:
           -o metadata/pr-title.md
           /dev/null
     - name: Generate PR Body
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       uses: docker://pandoc/core
       with:
         args: >-
@@ -281,7 +283,7 @@ runs:
           -o metadata/pr-body.md
           /dev/null
     - name: Generate Commit Message
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       uses: docker://pandoc/core
       with:
         args: >-
@@ -294,7 +296,7 @@ runs:
     # Print the populated pandoc templates to the GitHub Actions step summary.
     # (These will print on the "Summary" of a run of this Action.)
     - name: Show Metadata
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       shell: bash
       run: |
         echo "# PR Title" >> $GITHUB_STEP_SUMMARY
@@ -308,7 +310,7 @@ runs:
     # Using the information in the JSON Metadata, cherry-pick all commits from
     # the staging branch.
     - name: Cherry Pick Staging Branch Commits
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       shell: bash
       run: |
         cd downstream/
@@ -323,7 +325,7 @@ runs:
         done
     # Create unstaged changes that updates the CIRCT version to "latest".
     - name: Update Downstream Project to Latest Upstream Release
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       shell: bash
       run: |
         cd downstream/
@@ -342,7 +344,7 @@ runs:
       #
       # [4]: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
     - name: Setup Environment with Metadata
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       id: setup-env
       shell: bash
       run: |
@@ -358,7 +360,7 @@ runs:
     # Commit unstaged changes, create or update the PR, notify reviewers, and
     # add labels.
     - name: Create PR
-      if: steps.open-pr.outputs.result == 'yes'
+      if: steps.open-pr.outputs.result == 'true'
       id: create-pr
       uses: peter-evans/create-pull-request@v5
       with:
